# This file was generated by GoReleaser. DO NOT EDIT.
cask "httpstat" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "dff4afe928fc09619c497ac20a2a97e6e89b71c1426a7ca7688d55e8c352dbea"
      url "https://github.com/vandancd/httpstat/releases/download/v#{version}/httpstat_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4024a6b0766cd4d8493ee75fc9926064b208c85e3f15223abb474bfe67a6203c"
      url "https://github.com/vandancd/httpstat/releases/download/v#{version}/httpstat_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "07e3d6f634e052deda56097212730a24aa22663088d245394d8a3f3d0fd28e1d"
      url "https://github.com/vandancd/httpstat/releases/download/v#{version}/httpstat_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "63859de29dd7d3b8e3f5912d983170570904aafdebc001c45088e1b54f00e85c"
      url "https://github.com/vandancd/httpstat/releases/download/v#{version}/httpstat_linux_arm64.tar.gz"
    end
  end

  name "httpstat"
  desc "HTTP performance measurement tool with waterfall output and trace"
  homepage "https://github.com/vandancd/httpstat"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "httpstat"

  # No zap stanza required

end
